# Generated by Django 4.1.3 on 2022-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='history',
            field=models.TextField(null=True, verbose_name='Firm history'),
        ),
    ]
